export let promotions = [
   {
      id: 1,
      size: "1-gal btl.",
      desc1: "Any Variety, Fruit Juice Cocktail or Iced Tea",
      desc3: "Arizona Iced Tea",
      priceplus: "PRICE PLUS LIMIT 4 PER VARIETY",
      dr: "DR $ 0.70",
      projectedRetail: "795603",
      hasAdditionalCoupon: false,
      adzone1SalesRetail: "2.69",
      adzone1Discount: "0.70",
      adzone2SalesRetail: "2.69",
      adzone2Discount: "0.70",
      adzone3SalesRetail: "2.69",
      adzone3Discount: "0.70",
      eventName: "Front Page",
   },
   {
      id: 2,
      size:
         "15.25-oz. box (Excluding Original Recipe, Favorites, Angel Food & Premium Cupcake) Any Variety, Delights Cake Mix or 12-oz. to 1-lb. can, Ready to Spread Frosting",
      desc3: "Betty Crocker Delights Cake Mix or Frosting",
      priceplus: "PRICE PLUS LIMIT 4 PER VARIETY",
      dr: "DR $ 0.33",
      fsi: "FSI: 3/29 - Paper Coupon WTC 3/$3.00",
      projectedRetail: "559607",
      hasAdditionalCoupon: true,
      additionalCoupon1: "Paper $1.50",
      adzone1SalesRetail: "1.83",
      adzone1Discount: "0.33",
      adzone2SalesRetail: "1.83",
      adzone2Discount: "0.33",
      adzone3SalesRetail: "1.83",
      adzone3Discount: "0.33",
      eventName: "Front Page",
   },
   {
      id: 3,
      size: "34-ct. box",
      desc1: "Any Variety, Downy, Gain or Bounce",
      desc3: "Bounce Fabric Softener Sheets",
      projectedRetail: "38387",
      hasAdditionalCoupon: false,
      adzone1SalesRetail: "1.99",
      adzone2SalesRetail: "2.19",
      adzone3SalesRetail: "2.49",
      eventName: "Easter Locked in Savings",
   },
   {
      id: 4,
      size: "10.75-oz. can",
      desc1: "(Excluding Healthy Request & Less Sodium)",
      desc2: "Original Only",
      desc3: "Campbells Chicken Noodle or Tomato Soup",
      fsi: "FSI: 3/29 - 4 Day Digital Coupon, 2/$1.00 w/Digi, 1/2 Price, L4",
      projectedRetail: "339145",
      hasAdditionalCoupon: true,
      additionalCoupon1: "Digital $1.00",
      additionalCoupon2: "Must Buy 2",
      adzone1SalesRetail: "1.00",
      adzone2SalesRetail: "1.00",
      adzone3SalesRetail: "1.00",
      eventName: "Easter Locked in Savings",
   },
];

export let headerInfo = {
   adDate: "03/29/2020",
   week: 27,
   vehicle: "14 PG STD W/GATE CHAINWIDE",
   projectedSales: "19528465",
};
